language: ruby
sudo: false
cache: bundler
rvm:
  - 2.4.10
  - 2.5.8
  - 2.6
  - ruby-head
bundler_args: --without development
addons:
  code_climate:
    repo_token: 7af99d9225b4c14640f9ec3cb2e24d2f7103ac49417b0bd989188fb6c25f2909
after_success:
    - bundle exec codeclimate-test-reporter
matrix:
  allow_failures:
    rvm: ruby-head
